name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert names to lowercase
      id: lowercase
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        TAG_NAME=$(echo "${{ github.event.release.tag_name }}" | tr '[:upper:]' '[:lower:]')
        
        echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
        echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

    - name: Build Docker image
      id: build-image
      run: |
        docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ env.TAG_NAME }} .
        if [ "${{ github.event.release.prerelease }}" == "false" ]; then
          docker tag ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ env.TAG_NAME }} ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
        fi

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
        if [ "${{ github.event.release.prerelease }}" == "false" ]; then
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
        fi
